modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="nedaire"
version="${file.jarVersion}"
displayName="Nedaire"
displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="nedaire.png"
credits="Thanks for this example mod goes to Java"
authors="ArcAnc"
description='''
Description
'''
[[dependencies.nedaire]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.nedaire]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="BEFORE"
    side="BOTH"
